#!/usr/bin/env bash
# 07_wiki_setup.sh — Karpathy 3-layer wiki + Obsidian config + maintenance skills

set -euo pipefail

WORKSPACE="${WORKSPACE:-/mnt/c/Users/$(whoami)/Desktop/JESUSCORD}"
OBSIDIAN_VAULT="${OBSIDIAN_VAULT:-/mnt/c/Users/$(whoami)/Documents/Obsidian/Jesuscord}"
WIKI_DIR="$WORKSPACE/wiki"
SOURCES_DIR="$WORKSPACE/sources"

ALL_PROFILES=(boss supervisor hr conductor growth eng brand room-engine video distro sermons creators dev churches)

echo "=== KARPATHY WIKI SETUP ==="

# Layer 1
mkdir -p "$SOURCES_DIR"/{pastors,corpus,platforms,transcripts,public,inbound,manual_uploads}
for d in $(seq -f "%02g" 0 30); do
  date_str=$(date -d "+${d#0} days" +%Y-%m-%d 2>/dev/null || date +%Y-%m-%d)
  mkdir -p "$SOURCES_DIR/platforms/$date_str"
done
cat > "$SOURCES_DIR/_IMMUTABLE.md" <<'EOF'
# IMMUTABLE — Layer 1
Append, never edit. Corrections via _corr_<original>.md sidecars.
EOF
echo "[OK] Layer 1 sources/"

# Layer 2
mkdir -p "$WIKI_DIR"/{audience,voice,competitive,pastors,creators,churches,conferences,opportunities,campaigns,lessons,skills-library,branding,runbooks,feature_pipeline,memory-promotions,team_roster}

cat > "$WIKI_DIR/INDEX.md" <<'EOF'
# Jesuscord Wiki Index
Auto-regenerated by wiki-curator on every wiki write.

## Sections
- [[audience/]]
- [[voice/]]
- [[competitive/]]
- [[pastors/]] — target 1000
- [[creators/]] — target 200+
- [[churches/]] — target 700
- [[conferences/]]
- [[opportunities/]]
- [[campaigns/]]
- [[lessons/]]
- [[skills-library/]]
- [[branding/]]
- [[runbooks/]]
- [[feature_pipeline/]]
- [[memory-promotions/]]
- [[team_roster/]]
EOF

echo "[OK] Layer 2 wiki/"

# Obsidian vault symlink + config (also done by 01_install.sh; idempotent here)
mkdir -p "$(dirname "$OBSIDIAN_VAULT")"
if [[ ! -L "$OBSIDIAN_VAULT" ]]; then
  [[ -d "$OBSIDIAN_VAULT" ]] && mv "$OBSIDIAN_VAULT" "$OBSIDIAN_VAULT.bak.$(date +%s)"
  ln -s "$WIKI_DIR" "$OBSIDIAN_VAULT"
fi

mkdir -p "$WIKI_DIR/.obsidian" "$WIKI_DIR/.templates"

cat > "$WIKI_DIR/.obsidian/app.json" <<'EOF'
{"alwaysUpdateLinks": true, "newLinkFormat": "shortest", "useMarkdownLinks": false, "showInlineTitle": true, "showFrontmatter": true, "useTab": false, "tabSize": 2}
EOF
cat > "$WIKI_DIR/.obsidian/core-plugins.json" <<'EOF'
["file-explorer","global-search","switcher","graph","backlink","outgoing-link","tag-pane","page-preview","templates","outline","word-count","bookmarks"]
EOF
cat > "$WIKI_DIR/.obsidian/community-plugins.json" <<'EOF'
["dataview","templater-obsidian"]
EOF

cat > "$WIKI_DIR/.templates/pastor.md" <<'EOF'
---
title: <% tp.file.title %>
type: pastor
created_at: <% tp.date.now("YYYY-MM-DDTHH:mm:ssZ") %>
sources: []
confidence: medium
review_status: draft
clip_auth: false
---

# <% tp.file.title %>

## Identity
- Church:
- Denomination:
- Location:
- Languages:

## Reach
- Followers:
- Audience size:
- Primary platforms:

## Content
- Sermon archive URL:
- Podcast URL:
- Recent themes:

## 愛無線 relationship
- Status:
- Prior interactions:

## Notes
EOF

cat > "$WIKI_DIR/.templates/creator.md" <<'EOF'
---
title: <% tp.file.title %>
type: creator
created_at: <% tp.date.now("YYYY-MM-DDTHH:mm:ssZ") %>
sources: []
confidence: medium
review_status: draft
funnel_state: prospected
---

# <% tp.file.title %>

## Identity
- Niche:
- Platforms:
- Followers:

## Audience

## Outreach
- Status:
- Last contact:
- Next step:
EOF

cat > "$WIKI_DIR/.templates/church.md" <<'EOF'
---
title: <% tp.file.title %>
type: church
created_by: churches
created_at: <% tp.date.now("YYYY-MM-DDTHH:mm:ssZ") %>
sources: []
confidence: medium
review_status: draft
hub_status: prebuilt
---

# <% tp.file.title %>

## Public info
- Denomination:
- Location:
- Service times:
- Website:
- Sermon RSS:

## Hub status
- Pre-built:
- Notified:
- Claimed:
- Customized:

## Bots configured
- ContentBot:
- GreeterBot:
- DiscussionBot:
- PrayerBot:
EOF

echo "[OK] Obsidian configured"

# Wiki maintenance skills (installed across all 14 profiles)
install_skill() {
  local skill="$1" body="$2"
  for p in "${ALL_PROFILES[@]}"; do
    local dir="$HOME/.hermes-$p/skills/$skill"
    mkdir -p "$dir"
    echo "$body" > "$dir/SKILL.md"
  done
}

install_skill "wiki-write" '# wiki-write
Write or update a wiki page per Karpathy SCHEMA.md.

Steps:
1. Read SCHEMA.md
2. Determine target path under wiki/
3. If exists: read, merge, preserve frontmatter, update timestamp, append change-log
4. If new: write with full frontmatter
5. Use [[wikilinks]] for cross-refs
6. Trigger wiki-index-regen

Output: path + diff.
Refusals: no fabricated content. Mark unverified facts confidence: low. Never delete (deletions go through decision).
'

install_skill "wiki-index-regen" '# wiki-index-regen
Regenerate wiki/INDEX.md.

Steps:
1. Walk wiki/ recursively (skip .obsidian, .templates)
2. Per dir: count pages, last-updated
3. Per page: extract title, type, review_status from frontmatter
4. Identify issues: missing frontmatter, broken [[wikilinks]], no sources
5. Write INDEX.md
'

install_skill "promote-to-wiki" '# promote-to-wiki
Promote MEMORY.md fact to wiki page.

When: 3+ cross-session refs OR boss promotion OR skill output with promote: true.

Steps:
1. Read MEMORY.md, find fact
2. Determine target wiki section per SCHEMA.md
3. Write to wiki/<section>/<slug>.md with frontmatter
4. Add cross-refs to related pages
5. Append to wiki/memory-promotions/<date>.md
'

install_skill "contradiction-detector" '# contradiction-detector
Scan wiki/ for contradictions.

Steps:
1. For each pair of cross-referenced pages, extract assertions
2. Identify direct + soft contradictions
3. Write findings to wiki/INDEX.md#issues
4. High-confidence contradiction = decision-class escalation
'

install_skill "source-ingest" '# source-ingest
Process raw input from sources/inbound/ → relevant wiki pages.

Steps:
1. Read raw input
2. Classify: pastor / creator / church / competitive / trend / transcript
3. Extract structured facts
4. Per fact: new wiki page OR append OR MEMORY.md
5. Write with sources: [<inbound path>] frontmatter
6. Move processed input to sources/<category>/<dated>/
'

echo "[OK] 5 wiki maintenance skills installed across 14 profiles"

# Wiki maintenance cron (boss + hr)
HERMES_HOME="$HOME/.hermes-boss" hermes cron create \
  --name "wiki-index-regen" --schedule "*/15 * * * *" \
  --prompt "Run wiki-index-regen skill against $WIKI_DIR" 2>/dev/null || true
HERMES_HOME="$HOME/.hermes-boss" hermes cron create \
  --name "contradiction-scan" --schedule "0 */4 * * *" \
  --prompt "Run contradiction-detector skill" 2>/dev/null || true
HERMES_HOME="$HOME/.hermes-hr" hermes cron create \
  --name "source-ingest" --schedule "*/10 * * * *" \
  --prompt "Process sources/inbound/ via source-ingest skill" 2>/dev/null || true

echo "[OK] wiki maintenance cron registered"

cat <<EOF

============================================================
WIKI SETUP COMPLETE
============================================================
Layer 1 sources:    $SOURCES_DIR
Layer 2 wiki:       $WIKI_DIR
Layer 3 SCHEMA:     $WIKI_DIR/SCHEMA.md
Obsidian vault:     $OBSIDIAN_VAULT (symlink)

Open Obsidian → 'Open folder as vault' → $OBSIDIAN_VAULT
Wiki populates as factory runs.
============================================================
EOF
